### ISSUE TITLE
Need update browser

### ISSUE THREAD

**Issue by Mishasama** [pkviet/obs-studio#46] opened 2021-01-21 22:45 UTC
**Describe the bug**
https://v.douyu.com/show/a2JEMJjp5bnMNxml
The ME ver Browser source does not support the HTML5 player. But the OBSS 26.1.1 does.

**To Reproduce**
1. Add Browser source
2. Enter URL https://v.douyu.com/show/a2JEMJjp5bnMNxml
3. Click OK

**Expected behavior**
As the origin OBSS does.

**Screenshots**
![image](https://user-images.githubusercontent.com/54498172/105421288-3a182a00-5c85-11eb-9b2e-104cab4a6b26.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 1809

**Additional context**
Time to update to 26.1.1 and fix #42?

**Comment by pkviet** [comment] 2021-01-22 01:54
It's not an html5 player error since youtube html5 player works fine.
The browser version is exactly the same (what ships in 26.1.1 is exactly what ships with obs ME since I'm the one who compiled cef); this is very odd (though I reproduce your error).
What does the chinese say ? I guess "browser not supported" ?

**Comment by pkviet** [comment] 2021-01-22 02:09
seems your link freezes on chromium edge

**Comment by Mishasama** [comment] 2021-01-23 12:23
> It's not an html5 player error since youtube html5 player works fine.
> The browser version is exactly the same (what ships in 26.1.1 is exactly what ships with obs ME since I'm the one who compiled cef); this is very odd (though I reproduce your error).
> What does the chinese say ? I guess "browser not supported" ?

Youtube player is only play the vp9 video, but the avc can't. Maybe that's the problem.
"Your browser version is too low, please update it."
I tried to replace ME's browser plugin with the original version, and it works fine.

**Comment by pkviet** [comment] 2021-01-23 13:08
Mmh very very strange.
What did you replace ? Obs-browser.dll or cef ?

**Comment by pkviet** [comment] 2021-01-23 21:15
ok solved.
I found out that during the packaging I shipped a wrong version of cef library (although I'm the main compiler for obs-studio of the lib).
Thanks for the report. Will be fixed in next release.
Closing.

**Closed as completed by pkviet** 2021-01-23 21:15 UTC
