### ISSUE TITLE
[27.0.1] ASIO bug

### ISSUE THREAD

**Issue by Mishasama** [pkviet/obs-studio#60] opened 2021-07-17 00:21 UTC
The ASIO Input Capture looks not compatible with Realtek ASIO. It just crashes without any message. It only left this line in the log file.
![image](https://user-images.githubusercontent.com/54498172/126019424-ab2964dc-bb62-459a-9e3b-0324aed0c72b.png)

**Comment by pkviet** [comment] 2021-07-17 05:11
realtek asio works on my side ...
No idea why it's not working on yours.
![obs64_2021-07-17_07-09-33](https://user-images.githubusercontent.com/9283407/126026507-cdcfb617-8ae5-47c7-9de3-43e8b17d21fa.png)

**Comment by Mishasama** [comment] 2021-07-19 08:39
When I select the Realtek ASIO, my browser chrome will also stop playing sound/video. It looks like switching my default device, but my default device is another sound card.

**Comment by pkviet** [comment] 2021-09-08 09:35
dunno if the issue is still curent or not; closing now, feel free to reopen if you have further info.

**Closed as completed by pkviet** 2021-09-08 09:35 UTC
